    ##Configuration Docker (optionnel)

#services:
#  minio:
#    image: minio/minio
#    container_name: minio
#    ports:
#
#      - '9000:9000'
#      - '9001:9001'
#    environment:
#      MINIO_ROOT_USER: minioadmin
#      MINIO_ROOT_PASSWORD: minioadmin
#    volumes:
#      - 'minio_data:/data'
#    command: 'server /data --console-address ":9001"'
#    healthcheck:
#      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
#      interval: 30s
#      timeout: 20s
#      retries: 3
#
#    restart: unless-stopped
#
#volumes:
#  minio_data:
#    driver: local